// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.rees46.rees46_flutter_sdk.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PersonalizationApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class InitConfig (
  val shopId: String,
  val apiDomain: String,
  val stream: String,
  val enableLogs: Boolean,
  val autoSendPushToken: Boolean,
  val sendAdvertisingId: Boolean,
  val enableAutoPopupPresentation: Boolean,
  val needReInitialization: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitConfig {
      val shopId = pigeonVar_list[0] as String
      val apiDomain = pigeonVar_list[1] as String
      val stream = pigeonVar_list[2] as String
      val enableLogs = pigeonVar_list[3] as Boolean
      val autoSendPushToken = pigeonVar_list[4] as Boolean
      val sendAdvertisingId = pigeonVar_list[5] as Boolean
      val enableAutoPopupPresentation = pigeonVar_list[6] as Boolean
      val needReInitialization = pigeonVar_list[7] as Boolean
      return InitConfig(shopId, apiDomain, stream, enableLogs, autoSendPushToken, sendAdvertisingId, enableAutoPopupPresentation, needReInitialization)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shopId,
      apiDomain,
      stream,
      enableLogs,
      autoSendPushToken,
      sendAdvertisingId,
      enableAutoPopupPresentation,
      needReInitialization,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InitConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return PersonalizationApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Wire format for one purchase line (maps to native `PurchaseItemRequest`).
 * [amount] is the canonical line quantity; native's redundant `quantity` alias
 * is intentionally not exposed.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PurchaseLineItemWire (
  val id: String,
  /** Number of units of this product in the order (the line quantity). */
  val amount: Long,
  val price: Double,
  val lineId: String? = null,
  val fashionSize: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PurchaseLineItemWire {
      val id = pigeonVar_list[0] as String
      val amount = pigeonVar_list[1] as Long
      val price = pigeonVar_list[2] as Double
      val lineId = pigeonVar_list[3] as String?
      val fashionSize = pigeonVar_list[4] as String?
      return PurchaseLineItemWire(id, amount, price, lineId, fashionSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      amount,
      price,
      lineId,
      fashionSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PurchaseLineItemWire) {
      return false
    }
    if (this === other) {
      return true
    }
    return PersonalizationApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Wire format for profile fields sent to native SDK.
 * All fields are optional — only non-null values are forwarded.
 * [birthday] must be a "yyyy-MM-dd" string.
 * [gender] must be "m" or "f".
 * [customPropertiesJson] is a JSON object string or null.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProfileParamsWire (
  val email: String? = null,
  val phone: String? = null,
  val loyaltyId: String? = null,
  val firstName: String? = null,
  val lastName: String? = null,
  val birthday: String? = null,
  val age: Long? = null,
  val gender: String? = null,
  val location: String? = null,
  val advertisingId: String? = null,
  val fbId: String? = null,
  val vkId: String? = null,
  val telegramId: String? = null,
  val loyaltyCardLocation: String? = null,
  val loyaltyStatus: String? = null,
  val loyaltyBonuses: Long? = null,
  val loyaltyBonusesToNextLevel: Long? = null,
  val boughtSomething: Boolean? = null,
  val userId: String? = null,
  val customPropertiesJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileParamsWire {
      val email = pigeonVar_list[0] as String?
      val phone = pigeonVar_list[1] as String?
      val loyaltyId = pigeonVar_list[2] as String?
      val firstName = pigeonVar_list[3] as String?
      val lastName = pigeonVar_list[4] as String?
      val birthday = pigeonVar_list[5] as String?
      val age = pigeonVar_list[6] as Long?
      val gender = pigeonVar_list[7] as String?
      val location = pigeonVar_list[8] as String?
      val advertisingId = pigeonVar_list[9] as String?
      val fbId = pigeonVar_list[10] as String?
      val vkId = pigeonVar_list[11] as String?
      val telegramId = pigeonVar_list[12] as String?
      val loyaltyCardLocation = pigeonVar_list[13] as String?
      val loyaltyStatus = pigeonVar_list[14] as String?
      val loyaltyBonuses = pigeonVar_list[15] as Long?
      val loyaltyBonusesToNextLevel = pigeonVar_list[16] as Long?
      val boughtSomething = pigeonVar_list[17] as Boolean?
      val userId = pigeonVar_list[18] as String?
      val customPropertiesJson = pigeonVar_list[19] as String?
      return ProfileParamsWire(email, phone, loyaltyId, firstName, lastName, birthday, age, gender, location, advertisingId, fbId, vkId, telegramId, loyaltyCardLocation, loyaltyStatus, loyaltyBonuses, loyaltyBonusesToNextLevel, boughtSomething, userId, customPropertiesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      phone,
      loyaltyId,
      firstName,
      lastName,
      birthday,
      age,
      gender,
      location,
      advertisingId,
      fbId,
      vkId,
      telegramId,
      loyaltyCardLocation,
      loyaltyStatus,
      loyaltyBonuses,
      loyaltyBonusesToNextLevel,
      boughtSomething,
      userId,
      customPropertiesJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProfileParamsWire) {
      return false
    }
    if (this === other) {
      return true
    }
    return PersonalizationApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Wire format for one product line in a tracking event (maps to native `TrackingItem`).
 *
 * [quantity] is the domain name for the line quantity; native sends it as `amount`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrackingItemWire (
  val id: String,
  val quantity: Long,
  val price: Double? = null,
  val fashionSize: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingItemWire {
      val id = pigeonVar_list[0] as String
      val quantity = pigeonVar_list[1] as Long
      val price = pigeonVar_list[2] as Double?
      val fashionSize = pigeonVar_list[3] as String?
      return TrackingItemWire(id, quantity, price, fashionSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      quantity,
      price,
      fashionSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TrackingItemWire) {
      return false
    }
    if (this === other) {
      return true
    }
    return PersonalizationApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Wire format for event attribution (maps to native `TrackingSource`).
 *
 * [type] is the wire value of the source type — `dynamic`, `chain`, `bulk`,
 * `transactional`, `instant_search`, `full_search`, `stories`. Dart only ever sends what its
 * `TrackingSourceType` enum produces; the bridges reject anything else.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrackingSourceWire (
  val type: String,
  val code: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingSourceWire {
      val type = pigeonVar_list[0] as String
      val code = pigeonVar_list[1] as String
      return TrackingSourceWire(type, code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TrackingSourceWire) {
      return false
    }
    if (this === other) {
      return true
    }
    return PersonalizationApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PersonalizationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PurchaseLineItemWire.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileParamsWire.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingItemWire.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingSourceWire.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PurchaseLineItemWire -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ProfileParamsWire -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is TrackingItemWire -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TrackingSourceWire -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PersonalizationHostApi {
  fun initialize(config: InitConfig, callback: (Result<Unit>) -> Unit)
  fun getPlatformVersion(): String
  /** Returns the push token stored by the native SDK (if any). */
  fun getStoredPushToken(shopId: String?): String?
  /** [customFieldsJson] is JSON object string or null (maps to native custom fields map). */
  fun trackEvent(event: String, time: Long?, category: String?, label: String?, value: Long?, customFieldsJson: String?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun setProfile(params: ProfileParamsWire, shopId: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Returns the recommendation block as a JSON string.
   * [paramsJson] is a JSON object string with optional filter parameters.
   * Dart layer parses the result into [RecommendationResponse].
   */
  fun getRecommendation(code: String, paramsJson: String?, shopId: String?, callback: (Result<String>) -> Unit)
  /** Returns the current session ID from the native SDK. */
  fun getSid(shopId: String?): String
  /** Returns the device ID assigned by the native SDK, or null before first sync. */
  fun getDid(shopId: String?): String?
  /**
   * Returns a single product's details as a JSON string.
   * Dart layer parses the result into [Product].
   */
  fun getProductInfo(itemId: String, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns a paginated product catalog list as a JSON string.
   * [paramsJson] is a JSON object with optional filter fields.
   * Dart layer parses the result into [ProductsListResponse].
   */
  fun getProductsList(paramsJson: String?, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns blank search results (trending/popular) as a JSON string.
   * No parameters — the native SDK decides what to return based on shop config.
   * Dart layer parses the result into [SearchBlankResponse].
   */
  fun searchBlank(shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns instant (typeahead) search results as a JSON string.
   * [paramsJson] may contain optional "locations" (String) and "excluded_brands" ([String]).
   * Dart layer parses the result into [SearchInstantResponse].
   */
  fun searchInstant(query: String, paramsJson: String?, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns full search results as a JSON string.
   * [paramsJson] is a JSON object string with optional search parameters.
   * Dart layer parses the result into [SearchFullResponse].
   */
  fun searchFull(query: String, paramsJson: String?, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Joins the loyalty program (`loyalty/members/join`) and returns the
   * response envelope as a JSON string `{ "status": ..., "payload": { ... } }`.
   * The shop is identified by the SDK's configured `shop_id`; [phone] is required.
   * Dart layer parses the result into [LoyaltyJoinResponse].
   */
  fun joinLoyalty(phone: String, email: String?, firstName: String?, lastName: String?, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns the loyalty membership status (`loyalty/members/status`) as a JSON
   * string `{ "status": ..., "payload": { "member": ..., "level": { ... } } }`.
   * [identifier] is the member identifier (phone).
   * Dart layer parses the result into [LoyaltyStatusResponse].
   */
  fun getLoyaltyStatus(identifier: String, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns the current user's profile as a JSON string.
   * Dart layer parses the result into [ProfileResponse].
   */
  fun getProfile(shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns view / cart / purchase counters for [item] as a JSON string.
   * Dart layer parses the result into [ProductCountersResponse].
   */
  fun getProductCounters(item: String, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns a category product listing as a JSON string.
   * [limit] and [page] paginate the result; both are optional.
   * Dart layer parses the result into [CategoryResponse].
   */
  fun getCategory(category: String, limit: Long?, page: Long?, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Returns a merchandised collection's products as a JSON string.
   * Dart layer parses the result into [CollectionResponse].
   */
  fun getCollection(collectionId: String, shopId: String?, callback: (Result<String>) -> Unit)
  /**
   * Routes a push to the shop it belongs to (payload `shop_id`) and tracks it
   * via the native `Rees46.handlePush`. [event] is the index of the Dart
   * `PushEvent` enum: 0 = received, 1 = delivered, 2 = clicked. The native side
   * maps it to its own vocabulary (Android `PushEventType`, iOS `PushEvent`).
   */
  fun handlePush(payload: Map<String, String>, event: Long, callback: (Result<Unit>) -> Unit)
  fun trackProductView(itemId: String, source: TrackingSourceWire?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackCategoryView(categoryId: String, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackSearch(query: String, results: List<String>?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackAddToCart(item: TrackingItemWire, source: TrackingSourceWire?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackSyncCart(items: List<TrackingItemWire>, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackRemoveFromCart(itemId: String, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackAddToFavorites(itemId: String, source: TrackingSourceWire?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackSyncFavorites(itemIds: List<String>, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackRemoveFromFavorites(itemId: String, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackStoryView(storyId: String, slideId: String, code: String?, shopId: String?, callback: (Result<Unit>) -> Unit)
  fun trackStoryClick(storyId: String, slideId: String, code: String?, shopId: String?, callback: (Result<Unit>) -> Unit)
  /** Stores the attribution source natively for the next event. */
  fun trackSetSource(source: TrackingSourceWire, shopId: String?)
  /** [customJson] and [recommendedSourceJson] are JSON object strings or null. */
  fun trackPurchase(orderId: String, orderPrice: Double, items: List<PurchaseLineItemWire>, deliveryType: String?, deliveryAddress: String?, paymentType: String?, isTaxFree: Boolean, isGiftPackage: Boolean, promocode: String?, orderCash: Double?, orderBonuses: Double?, orderDelivery: Double?, orderDiscount: Double?, channel: String?, customJson: String?, recommendedSourceJson: String?, stream: String?, segment: String?, shopId: String?, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PersonalizationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PersonalizationApiPigeonCodec()
    }
    /** Sets up an instance of `PersonalizationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PersonalizationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as InitConfig
            api.initialize(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPlatformVersion())
            } catch (exception: Throwable) {
              PersonalizationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getStoredPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shopIdArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getStoredPushToken(shopIdArg))
            } catch (exception: Throwable) {
              PersonalizationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventArg = args[0] as String
            val timeArg = args[1] as Long?
            val categoryArg = args[2] as String?
            val labelArg = args[3] as String?
            val valueArg = args[4] as Long?
            val customFieldsJsonArg = args[5] as String?
            val shopIdArg = args[6] as String?
            api.trackEvent(eventArg, timeArg, categoryArg, labelArg, valueArg, customFieldsJsonArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.setProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as ProfileParamsWire
            val shopIdArg = args[1] as String?
            api.setProfile(paramsArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getRecommendation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeArg = args[0] as String
            val paramsJsonArg = args[1] as String?
            val shopIdArg = args[2] as String?
            api.getRecommendation(codeArg, paramsJsonArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getSid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shopIdArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getSid(shopIdArg))
            } catch (exception: Throwable) {
              PersonalizationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getDid$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shopIdArg = args[0] as String?
            val wrapped: List<Any?> = try {
              listOf(api.getDid(shopIdArg))
            } catch (exception: Throwable) {
              PersonalizationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.getProductInfo(itemIdArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductsList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsJsonArg = args[0] as String?
            val shopIdArg = args[1] as String?
            api.getProductsList(paramsJsonArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchBlank$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shopIdArg = args[0] as String?
            api.searchBlank(shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchInstant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val paramsJsonArg = args[1] as String?
            val shopIdArg = args[2] as String?
            api.searchInstant(queryArg, paramsJsonArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchFull$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val paramsJsonArg = args[1] as String?
            val shopIdArg = args[2] as String?
            api.searchFull(queryArg, paramsJsonArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.joinLoyalty$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phoneArg = args[0] as String
            val emailArg = args[1] as String?
            val firstNameArg = args[2] as String?
            val lastNameArg = args[3] as String?
            val shopIdArg = args[4] as String?
            api.joinLoyalty(phoneArg, emailArg, firstNameArg, lastNameArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getLoyaltyStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identifierArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.getLoyaltyStatus(identifierArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val shopIdArg = args[0] as String?
            api.getProfile(shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductCounters$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.getProductCounters(itemArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getCategory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val categoryArg = args[0] as String
            val limitArg = args[1] as Long?
            val pageArg = args[2] as Long?
            val shopIdArg = args[3] as String?
            api.getCategory(categoryArg, limitArg, pageArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getCollection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val collectionIdArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.getCollection(collectionIdArg, shopIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.handlePush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as Map<String, String>
            val eventArg = args[1] as Long
            api.handlePush(payloadArg, eventArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackProductView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as String
            val sourceArg = args[1] as TrackingSourceWire?
            val shopIdArg = args[2] as String?
            api.trackProductView(itemIdArg, sourceArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackCategoryView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val categoryIdArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.trackCategoryView(categoryIdArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSearch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val resultsArg = args[1] as List<String>?
            val shopIdArg = args[2] as String?
            api.trackSearch(queryArg, resultsArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackAddToCart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemArg = args[0] as TrackingItemWire
            val sourceArg = args[1] as TrackingSourceWire?
            val shopIdArg = args[2] as String?
            api.trackAddToCart(itemArg, sourceArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSyncCart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemsArg = args[0] as List<TrackingItemWire>
            val shopIdArg = args[1] as String?
            api.trackSyncCart(itemsArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackRemoveFromCart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.trackRemoveFromCart(itemIdArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackAddToFavorites$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as String
            val sourceArg = args[1] as TrackingSourceWire?
            val shopIdArg = args[2] as String?
            api.trackAddToFavorites(itemIdArg, sourceArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSyncFavorites$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdsArg = args[0] as List<String>
            val shopIdArg = args[1] as String?
            api.trackSyncFavorites(itemIdsArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackRemoveFromFavorites$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as String
            val shopIdArg = args[1] as String?
            api.trackRemoveFromFavorites(itemIdArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackStoryView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val storyIdArg = args[0] as String
            val slideIdArg = args[1] as String
            val codeArg = args[2] as String?
            val shopIdArg = args[3] as String?
            api.trackStoryView(storyIdArg, slideIdArg, codeArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackStoryClick$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val storyIdArg = args[0] as String
            val slideIdArg = args[1] as String
            val codeArg = args[2] as String?
            val shopIdArg = args[3] as String?
            api.trackStoryClick(storyIdArg, slideIdArg, codeArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSetSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as TrackingSourceWire
            val shopIdArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.trackSetSource(sourceArg, shopIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PersonalizationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val orderIdArg = args[0] as String
            val orderPriceArg = args[1] as Double
            val itemsArg = args[2] as List<PurchaseLineItemWire>
            val deliveryTypeArg = args[3] as String?
            val deliveryAddressArg = args[4] as String?
            val paymentTypeArg = args[5] as String?
            val isTaxFreeArg = args[6] as Boolean
            val isGiftPackageArg = args[7] as Boolean
            val promocodeArg = args[8] as String?
            val orderCashArg = args[9] as Double?
            val orderBonusesArg = args[10] as Double?
            val orderDeliveryArg = args[11] as Double?
            val orderDiscountArg = args[12] as Double?
            val channelArg = args[13] as String?
            val customJsonArg = args[14] as String?
            val recommendedSourceJsonArg = args[15] as String?
            val streamArg = args[16] as String?
            val segmentArg = args[17] as String?
            val shopIdArg = args[18] as String?
            api.trackPurchase(orderIdArg, orderPriceArg, itemsArg, deliveryTypeArg, deliveryAddressArg, paymentTypeArg, isTaxFreeArg, isGiftPackageArg, promocodeArg, orderCashArg, orderBonusesArg, orderDeliveryArg, orderDiscountArg, channelArg, customJsonArg, recommendedSourceJsonArg, streamArg, segmentArg, shopIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PersonalizationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PersonalizationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PersonalizationFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PersonalizationFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PersonalizationApiPigeonCodec()
    }
  }
  fun onPushReceived(shopIdArg: String?, payloadArg: Map<String, String?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(shopIdArg, payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PersonalizationApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPushDelivered(shopIdArg: String?, payloadArg: Map<String, String?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushDelivered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(shopIdArg, payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PersonalizationApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPushClicked(shopIdArg: String?, payloadArg: Map<String, String?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushClicked$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(shopIdArg, payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PersonalizationApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
