// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPersonalizationApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPersonalizationApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPersonalizationApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPersonalizationApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPersonalizationApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPersonalizationApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct InitConfig: Hashable {
  var shopId: String
  var apiDomain: String
  var stream: String
  var enableLogs: Bool
  var autoSendPushToken: Bool
  var sendAdvertisingId: Bool
  var enableAutoPopupPresentation: Bool
  var needReInitialization: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitConfig? {
    let shopId = pigeonVar_list[0] as! String
    let apiDomain = pigeonVar_list[1] as! String
    let stream = pigeonVar_list[2] as! String
    let enableLogs = pigeonVar_list[3] as! Bool
    let autoSendPushToken = pigeonVar_list[4] as! Bool
    let sendAdvertisingId = pigeonVar_list[5] as! Bool
    let enableAutoPopupPresentation = pigeonVar_list[6] as! Bool
    let needReInitialization = pigeonVar_list[7] as! Bool

    return InitConfig(
      shopId: shopId,
      apiDomain: apiDomain,
      stream: stream,
      enableLogs: enableLogs,
      autoSendPushToken: autoSendPushToken,
      sendAdvertisingId: sendAdvertisingId,
      enableAutoPopupPresentation: enableAutoPopupPresentation,
      needReInitialization: needReInitialization
    )
  }
  func toList() -> [Any?] {
    return [
      shopId,
      apiDomain,
      stream,
      enableLogs,
      autoSendPushToken,
      sendAdvertisingId,
      enableAutoPopupPresentation,
      needReInitialization,
    ]
  }
  static func == (lhs: InitConfig, rhs: InitConfig) -> Bool {
    return deepEqualsPersonalizationApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPersonalizationApi(value: toList(), hasher: &hasher)
  }
}

/// Wire format for one purchase line (maps to native `PurchaseItemRequest`).
/// [amount] is the canonical line quantity; native's redundant `quantity` alias
/// is intentionally not exposed.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PurchaseLineItemWire: Hashable {
  var id: String
  /// Number of units of this product in the order (the line quantity).
  var amount: Int64
  var price: Double
  var lineId: String? = nil
  var fashionSize: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PurchaseLineItemWire? {
    let id = pigeonVar_list[0] as! String
    let amount = pigeonVar_list[1] as! Int64
    let price = pigeonVar_list[2] as! Double
    let lineId: String? = nilOrValue(pigeonVar_list[3])
    let fashionSize: String? = nilOrValue(pigeonVar_list[4])

    return PurchaseLineItemWire(
      id: id,
      amount: amount,
      price: price,
      lineId: lineId,
      fashionSize: fashionSize
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      amount,
      price,
      lineId,
      fashionSize,
    ]
  }
  static func == (lhs: PurchaseLineItemWire, rhs: PurchaseLineItemWire) -> Bool {
    return deepEqualsPersonalizationApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPersonalizationApi(value: toList(), hasher: &hasher)
  }
}

/// Wire format for profile fields sent to native SDK.
/// All fields are optional — only non-null values are forwarded.
/// [birthday] must be a "yyyy-MM-dd" string.
/// [gender] must be "m" or "f".
/// [customPropertiesJson] is a JSON object string or null.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ProfileParamsWire: Hashable {
  var email: String? = nil
  var phone: String? = nil
  var loyaltyId: String? = nil
  var firstName: String? = nil
  var lastName: String? = nil
  var birthday: String? = nil
  var age: Int64? = nil
  var gender: String? = nil
  var location: String? = nil
  var advertisingId: String? = nil
  var fbId: String? = nil
  var vkId: String? = nil
  var telegramId: String? = nil
  var loyaltyCardLocation: String? = nil
  var loyaltyStatus: String? = nil
  var loyaltyBonuses: Int64? = nil
  var loyaltyBonusesToNextLevel: Int64? = nil
  var boughtSomething: Bool? = nil
  var userId: String? = nil
  var customPropertiesJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileParamsWire? {
    let email: String? = nilOrValue(pigeonVar_list[0])
    let phone: String? = nilOrValue(pigeonVar_list[1])
    let loyaltyId: String? = nilOrValue(pigeonVar_list[2])
    let firstName: String? = nilOrValue(pigeonVar_list[3])
    let lastName: String? = nilOrValue(pigeonVar_list[4])
    let birthday: String? = nilOrValue(pigeonVar_list[5])
    let age: Int64? = nilOrValue(pigeonVar_list[6])
    let gender: String? = nilOrValue(pigeonVar_list[7])
    let location: String? = nilOrValue(pigeonVar_list[8])
    let advertisingId: String? = nilOrValue(pigeonVar_list[9])
    let fbId: String? = nilOrValue(pigeonVar_list[10])
    let vkId: String? = nilOrValue(pigeonVar_list[11])
    let telegramId: String? = nilOrValue(pigeonVar_list[12])
    let loyaltyCardLocation: String? = nilOrValue(pigeonVar_list[13])
    let loyaltyStatus: String? = nilOrValue(pigeonVar_list[14])
    let loyaltyBonuses: Int64? = nilOrValue(pigeonVar_list[15])
    let loyaltyBonusesToNextLevel: Int64? = nilOrValue(pigeonVar_list[16])
    let boughtSomething: Bool? = nilOrValue(pigeonVar_list[17])
    let userId: String? = nilOrValue(pigeonVar_list[18])
    let customPropertiesJson: String? = nilOrValue(pigeonVar_list[19])

    return ProfileParamsWire(
      email: email,
      phone: phone,
      loyaltyId: loyaltyId,
      firstName: firstName,
      lastName: lastName,
      birthday: birthday,
      age: age,
      gender: gender,
      location: location,
      advertisingId: advertisingId,
      fbId: fbId,
      vkId: vkId,
      telegramId: telegramId,
      loyaltyCardLocation: loyaltyCardLocation,
      loyaltyStatus: loyaltyStatus,
      loyaltyBonuses: loyaltyBonuses,
      loyaltyBonusesToNextLevel: loyaltyBonusesToNextLevel,
      boughtSomething: boughtSomething,
      userId: userId,
      customPropertiesJson: customPropertiesJson
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      phone,
      loyaltyId,
      firstName,
      lastName,
      birthday,
      age,
      gender,
      location,
      advertisingId,
      fbId,
      vkId,
      telegramId,
      loyaltyCardLocation,
      loyaltyStatus,
      loyaltyBonuses,
      loyaltyBonusesToNextLevel,
      boughtSomething,
      userId,
      customPropertiesJson,
    ]
  }
  static func == (lhs: ProfileParamsWire, rhs: ProfileParamsWire) -> Bool {
    return deepEqualsPersonalizationApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPersonalizationApi(value: toList(), hasher: &hasher)
  }
}

/// Wire format for one product line in a tracking event (maps to native `TrackingItem`).
///
/// [quantity] is the domain name for the line quantity; native sends it as `amount`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TrackingItemWire: Hashable {
  var id: String
  var quantity: Int64
  var price: Double? = nil
  var fashionSize: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackingItemWire? {
    let id = pigeonVar_list[0] as! String
    let quantity = pigeonVar_list[1] as! Int64
    let price: Double? = nilOrValue(pigeonVar_list[2])
    let fashionSize: String? = nilOrValue(pigeonVar_list[3])

    return TrackingItemWire(
      id: id,
      quantity: quantity,
      price: price,
      fashionSize: fashionSize
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      quantity,
      price,
      fashionSize,
    ]
  }
  static func == (lhs: TrackingItemWire, rhs: TrackingItemWire) -> Bool {
    return deepEqualsPersonalizationApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPersonalizationApi(value: toList(), hasher: &hasher)
  }
}

/// Wire format for event attribution (maps to native `TrackingSource`).
///
/// [type] is the wire value of the source type — `dynamic`, `chain`, `bulk`,
/// `transactional`, `instant_search`, `full_search`, `stories`. Dart only ever sends what its
/// `TrackingSourceType` enum produces; the bridges reject anything else.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TrackingSourceWire: Hashable {
  var type: String
  var code: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackingSourceWire? {
    let type = pigeonVar_list[0] as! String
    let code = pigeonVar_list[1] as! String

    return TrackingSourceWire(
      type: type,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      code,
    ]
  }
  static func == (lhs: TrackingSourceWire, rhs: TrackingSourceWire) -> Bool {
    return deepEqualsPersonalizationApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPersonalizationApi(value: toList(), hasher: &hasher)
  }
}

private class PersonalizationApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return PurchaseLineItemWire.fromList(self.readValue() as! [Any?])
    case 131:
      return ProfileParamsWire.fromList(self.readValue() as! [Any?])
    case 132:
      return TrackingItemWire.fromList(self.readValue() as! [Any?])
    case 133:
      return TrackingSourceWire.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PersonalizationApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PurchaseLineItemWire {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileParamsWire {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TrackingItemWire {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? TrackingSourceWire {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PersonalizationApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PersonalizationApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PersonalizationApiPigeonCodecWriter(data: data)
  }
}

class PersonalizationApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PersonalizationApiPigeonCodec(readerWriter: PersonalizationApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PersonalizationHostApi {
  func initialize(config: InitConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func getPlatformVersion() throws -> String
  /// Returns the push token stored by the native SDK (if any).
  func getStoredPushToken(shopId: String?) throws -> String?
  /// [customFieldsJson] is JSON object string or null (maps to native custom fields map).
  func trackEvent(event: String, time: Int64?, category: String?, label: String?, value: Int64?, customFieldsJson: String?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func setProfile(params: ProfileParamsWire, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns the recommendation block as a JSON string.
  /// [paramsJson] is a JSON object string with optional filter parameters.
  /// Dart layer parses the result into [RecommendationResponse].
  func getRecommendation(code: String, paramsJson: String?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns the current session ID from the native SDK.
  func getSid(shopId: String?) throws -> String
  /// Returns the device ID assigned by the native SDK, or null before first sync.
  func getDid(shopId: String?) throws -> String?
  /// Returns a single product's details as a JSON string.
  /// Dart layer parses the result into [Product].
  func getProductInfo(itemId: String, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns a paginated product catalog list as a JSON string.
  /// [paramsJson] is a JSON object with optional filter fields.
  /// Dart layer parses the result into [ProductsListResponse].
  func getProductsList(paramsJson: String?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns blank search results (trending/popular) as a JSON string.
  /// No parameters — the native SDK decides what to return based on shop config.
  /// Dart layer parses the result into [SearchBlankResponse].
  func searchBlank(shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns instant (typeahead) search results as a JSON string.
  /// [paramsJson] may contain optional "locations" (String) and "excluded_brands" ([String]).
  /// Dart layer parses the result into [SearchInstantResponse].
  func searchInstant(query: String, paramsJson: String?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns full search results as a JSON string.
  /// [paramsJson] is a JSON object string with optional search parameters.
  /// Dart layer parses the result into [SearchFullResponse].
  func searchFull(query: String, paramsJson: String?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Joins the loyalty program (`loyalty/members/join`) and returns the
  /// response envelope as a JSON string `{ "status": ..., "payload": { ... } }`.
  /// The shop is identified by the SDK's configured `shop_id`; [phone] is required.
  /// Dart layer parses the result into [LoyaltyJoinResponse].
  func joinLoyalty(phone: String, email: String?, firstName: String?, lastName: String?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns the loyalty membership status (`loyalty/members/status`) as a JSON
  /// string `{ "status": ..., "payload": { "member": ..., "level": { ... } } }`.
  /// [identifier] is the member identifier (phone).
  /// Dart layer parses the result into [LoyaltyStatusResponse].
  func getLoyaltyStatus(identifier: String, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns the current user's profile as a JSON string.
  /// Dart layer parses the result into [ProfileResponse].
  func getProfile(shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns view / cart / purchase counters for [item] as a JSON string.
  /// Dart layer parses the result into [ProductCountersResponse].
  func getProductCounters(item: String, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns a category product listing as a JSON string.
  /// [limit] and [page] paginate the result; both are optional.
  /// Dart layer parses the result into [CategoryResponse].
  func getCategory(category: String, limit: Int64?, page: Int64?, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns a merchandised collection's products as a JSON string.
  /// Dart layer parses the result into [CollectionResponse].
  func getCollection(collectionId: String, shopId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Routes a push to the shop it belongs to (payload `shop_id`) and tracks it
  /// via the native `Rees46.handlePush`. [event] is the index of the Dart
  /// `PushEvent` enum: 0 = received, 1 = delivered, 2 = clicked. The native side
  /// maps it to its own vocabulary (Android `PushEventType`, iOS `PushEvent`).
  func handlePush(payload: [String: String], event: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func trackProductView(itemId: String, source: TrackingSourceWire?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackCategoryView(categoryId: String, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackSearch(query: String, results: [String]?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackAddToCart(item: TrackingItemWire, source: TrackingSourceWire?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackSyncCart(items: [TrackingItemWire], shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackRemoveFromCart(itemId: String, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackAddToFavorites(itemId: String, source: TrackingSourceWire?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackSyncFavorites(itemIds: [String], shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackRemoveFromFavorites(itemId: String, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackStoryView(storyId: String, slideId: String, code: String?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func trackStoryClick(storyId: String, slideId: String, code: String?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Stores the attribution source natively for the next event.
  func trackSetSource(source: TrackingSourceWire, shopId: String?) throws
  /// [customJson] and [recommendedSourceJson] are JSON object strings or null.
  func trackPurchase(orderId: String, orderPrice: Double, items: [PurchaseLineItemWire], deliveryType: String?, deliveryAddress: String?, paymentType: String?, isTaxFree: Bool, isGiftPackage: Bool, promocode: String?, orderCash: Double?, orderBonuses: Double?, orderDelivery: Double?, orderDiscount: Double?, channel: String?, customJson: String?, recommendedSourceJson: String?, stream: String?, segment: String?, shopId: String?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PersonalizationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PersonalizationApiPigeonCodec.shared }
  /// Sets up an instance of `PersonalizationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PersonalizationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! InitConfig
        api.initialize(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
    /// Returns the push token stored by the native SDK (if any).
    let getStoredPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getStoredPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStoredPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shopIdArg: String? = nilOrValue(args[0])
        do {
          let result = try api.getStoredPushToken(shopId: shopIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStoredPushTokenChannel.setMessageHandler(nil)
    }
    /// [customFieldsJson] is JSON object string or null (maps to native custom fields map).
    let trackEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventArg = args[0] as! String
        let timeArg: Int64? = nilOrValue(args[1])
        let categoryArg: String? = nilOrValue(args[2])
        let labelArg: String? = nilOrValue(args[3])
        let valueArg: Int64? = nilOrValue(args[4])
        let customFieldsJsonArg: String? = nilOrValue(args[5])
        let shopIdArg: String? = nilOrValue(args[6])
        api.trackEvent(event: eventArg, time: timeArg, category: categoryArg, label: labelArg, value: valueArg, customFieldsJson: customFieldsJsonArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackEventChannel.setMessageHandler(nil)
    }
    let setProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.setProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! ProfileParamsWire
        let shopIdArg: String? = nilOrValue(args[1])
        api.setProfile(params: paramsArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setProfileChannel.setMessageHandler(nil)
    }
    /// Returns the recommendation block as a JSON string.
    /// [paramsJson] is a JSON object string with optional filter parameters.
    /// Dart layer parses the result into [RecommendationResponse].
    let getRecommendationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getRecommendation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRecommendationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let codeArg = args[0] as! String
        let paramsJsonArg: String? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.getRecommendation(code: codeArg, paramsJson: paramsJsonArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRecommendationChannel.setMessageHandler(nil)
    }
    /// Returns the current session ID from the native SDK.
    let getSidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getSid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSidChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shopIdArg: String? = nilOrValue(args[0])
        do {
          let result = try api.getSid(shopId: shopIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSidChannel.setMessageHandler(nil)
    }
    /// Returns the device ID assigned by the native SDK, or null before first sync.
    let getDidChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getDid\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDidChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shopIdArg: String? = nilOrValue(args[0])
        do {
          let result = try api.getDid(shopId: shopIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDidChannel.setMessageHandler(nil)
    }
    /// Returns a single product's details as a JSON string.
    /// Dart layer parses the result into [Product].
    let getProductInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProductInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.getProductInfo(itemId: itemIdArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProductInfoChannel.setMessageHandler(nil)
    }
    /// Returns a paginated product catalog list as a JSON string.
    /// [paramsJson] is a JSON object with optional filter fields.
    /// Dart layer parses the result into [ProductsListResponse].
    let getProductsListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductsList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProductsListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsJsonArg: String? = nilOrValue(args[0])
        let shopIdArg: String? = nilOrValue(args[1])
        api.getProductsList(paramsJson: paramsJsonArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProductsListChannel.setMessageHandler(nil)
    }
    /// Returns blank search results (trending/popular) as a JSON string.
    /// No parameters — the native SDK decides what to return based on shop config.
    /// Dart layer parses the result into [SearchBlankResponse].
    let searchBlankChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchBlank\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchBlankChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shopIdArg: String? = nilOrValue(args[0])
        api.searchBlank(shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchBlankChannel.setMessageHandler(nil)
    }
    /// Returns instant (typeahead) search results as a JSON string.
    /// [paramsJson] may contain optional "locations" (String) and "excluded_brands" ([String]).
    /// Dart layer parses the result into [SearchInstantResponse].
    let searchInstantChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchInstant\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchInstantChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        let paramsJsonArg: String? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.searchInstant(query: queryArg, paramsJson: paramsJsonArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchInstantChannel.setMessageHandler(nil)
    }
    /// Returns full search results as a JSON string.
    /// [paramsJson] is a JSON object string with optional search parameters.
    /// Dart layer parses the result into [SearchFullResponse].
    let searchFullChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.searchFull\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchFullChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        let paramsJsonArg: String? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.searchFull(query: queryArg, paramsJson: paramsJsonArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchFullChannel.setMessageHandler(nil)
    }
    /// Joins the loyalty program (`loyalty/members/join`) and returns the
    /// response envelope as a JSON string `{ "status": ..., "payload": { ... } }`.
    /// The shop is identified by the SDK's configured `shop_id`; [phone] is required.
    /// Dart layer parses the result into [LoyaltyJoinResponse].
    let joinLoyaltyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.joinLoyalty\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      joinLoyaltyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let phoneArg = args[0] as! String
        let emailArg: String? = nilOrValue(args[1])
        let firstNameArg: String? = nilOrValue(args[2])
        let lastNameArg: String? = nilOrValue(args[3])
        let shopIdArg: String? = nilOrValue(args[4])
        api.joinLoyalty(phone: phoneArg, email: emailArg, firstName: firstNameArg, lastName: lastNameArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      joinLoyaltyChannel.setMessageHandler(nil)
    }
    /// Returns the loyalty membership status (`loyalty/members/status`) as a JSON
    /// string `{ "status": ..., "payload": { "member": ..., "level": { ... } } }`.
    /// [identifier] is the member identifier (phone).
    /// Dart layer parses the result into [LoyaltyStatusResponse].
    let getLoyaltyStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getLoyaltyStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLoyaltyStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifierArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.getLoyaltyStatus(identifier: identifierArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getLoyaltyStatusChannel.setMessageHandler(nil)
    }
    /// Returns the current user's profile as a JSON string.
    /// Dart layer parses the result into [ProfileResponse].
    let getProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shopIdArg: String? = nilOrValue(args[0])
        api.getProfile(shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProfileChannel.setMessageHandler(nil)
    }
    /// Returns view / cart / purchase counters for [item] as a JSON string.
    /// Dart layer parses the result into [ProductCountersResponse].
    let getProductCountersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getProductCounters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProductCountersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.getProductCounters(item: itemArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProductCountersChannel.setMessageHandler(nil)
    }
    /// Returns a category product listing as a JSON string.
    /// [limit] and [page] paginate the result; both are optional.
    /// Dart layer parses the result into [CategoryResponse].
    let getCategoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getCategory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCategoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let categoryArg = args[0] as! String
        let limitArg: Int64? = nilOrValue(args[1])
        let pageArg: Int64? = nilOrValue(args[2])
        let shopIdArg: String? = nilOrValue(args[3])
        api.getCategory(category: categoryArg, limit: limitArg, page: pageArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCategoryChannel.setMessageHandler(nil)
    }
    /// Returns a merchandised collection's products as a JSON string.
    /// Dart layer parses the result into [CollectionResponse].
    let getCollectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.getCollection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCollectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let collectionIdArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.getCollection(collectionId: collectionIdArg, shopId: shopIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCollectionChannel.setMessageHandler(nil)
    }
    /// Routes a push to the shop it belongs to (payload `shop_id`) and tracks it
    /// via the native `Rees46.handlePush`. [event] is the index of the Dart
    /// `PushEvent` enum: 0 = received, 1 = delivered, 2 = clicked. The native side
    /// maps it to its own vocabulary (Android `PushEventType`, iOS `PushEvent`).
    let handlePushChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.handlePush\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePushChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! [String: String]
        let eventArg = args[1] as! Int64
        api.handlePush(payload: payloadArg, event: eventArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handlePushChannel.setMessageHandler(nil)
    }
    let trackProductViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackProductView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackProductViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! String
        let sourceArg: TrackingSourceWire? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.trackProductView(itemId: itemIdArg, source: sourceArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackProductViewChannel.setMessageHandler(nil)
    }
    let trackCategoryViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackCategoryView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackCategoryViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let categoryIdArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.trackCategoryView(categoryId: categoryIdArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackCategoryViewChannel.setMessageHandler(nil)
    }
    let trackSearchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSearch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackSearchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        let resultsArg: [String]? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.trackSearch(query: queryArg, results: resultsArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackSearchChannel.setMessageHandler(nil)
    }
    let trackAddToCartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackAddToCart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackAddToCartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemArg = args[0] as! TrackingItemWire
        let sourceArg: TrackingSourceWire? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.trackAddToCart(item: itemArg, source: sourceArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackAddToCartChannel.setMessageHandler(nil)
    }
    let trackSyncCartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSyncCart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackSyncCartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemsArg = args[0] as! [TrackingItemWire]
        let shopIdArg: String? = nilOrValue(args[1])
        api.trackSyncCart(items: itemsArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackSyncCartChannel.setMessageHandler(nil)
    }
    let trackRemoveFromCartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackRemoveFromCart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackRemoveFromCartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.trackRemoveFromCart(itemId: itemIdArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackRemoveFromCartChannel.setMessageHandler(nil)
    }
    let trackAddToFavoritesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackAddToFavorites\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackAddToFavoritesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! String
        let sourceArg: TrackingSourceWire? = nilOrValue(args[1])
        let shopIdArg: String? = nilOrValue(args[2])
        api.trackAddToFavorites(itemId: itemIdArg, source: sourceArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackAddToFavoritesChannel.setMessageHandler(nil)
    }
    let trackSyncFavoritesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSyncFavorites\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackSyncFavoritesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdsArg = args[0] as! [String]
        let shopIdArg: String? = nilOrValue(args[1])
        api.trackSyncFavorites(itemIds: itemIdsArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackSyncFavoritesChannel.setMessageHandler(nil)
    }
    let trackRemoveFromFavoritesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackRemoveFromFavorites\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackRemoveFromFavoritesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! String
        let shopIdArg: String? = nilOrValue(args[1])
        api.trackRemoveFromFavorites(itemId: itemIdArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackRemoveFromFavoritesChannel.setMessageHandler(nil)
    }
    let trackStoryViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackStoryView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackStoryViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let storyIdArg = args[0] as! String
        let slideIdArg = args[1] as! String
        let codeArg: String? = nilOrValue(args[2])
        let shopIdArg: String? = nilOrValue(args[3])
        api.trackStoryView(storyId: storyIdArg, slideId: slideIdArg, code: codeArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackStoryViewChannel.setMessageHandler(nil)
    }
    let trackStoryClickChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackStoryClick\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackStoryClickChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let storyIdArg = args[0] as! String
        let slideIdArg = args[1] as! String
        let codeArg: String? = nilOrValue(args[2])
        let shopIdArg: String? = nilOrValue(args[3])
        api.trackStoryClick(storyId: storyIdArg, slideId: slideIdArg, code: codeArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackStoryClickChannel.setMessageHandler(nil)
    }
    /// Stores the attribution source natively for the next event.
    let trackSetSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackSetSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackSetSourceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! TrackingSourceWire
        let shopIdArg: String? = nilOrValue(args[1])
        do {
          try api.trackSetSource(source: sourceArg, shopId: shopIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackSetSourceChannel.setMessageHandler(nil)
    }
    /// [customJson] and [recommendedSourceJson] are JSON object strings or null.
    let trackPurchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationHostApi.trackPurchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackPurchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let orderIdArg = args[0] as! String
        let orderPriceArg = args[1] as! Double
        let itemsArg = args[2] as! [PurchaseLineItemWire]
        let deliveryTypeArg: String? = nilOrValue(args[3])
        let deliveryAddressArg: String? = nilOrValue(args[4])
        let paymentTypeArg: String? = nilOrValue(args[5])
        let isTaxFreeArg = args[6] as! Bool
        let isGiftPackageArg = args[7] as! Bool
        let promocodeArg: String? = nilOrValue(args[8])
        let orderCashArg: Double? = nilOrValue(args[9])
        let orderBonusesArg: Double? = nilOrValue(args[10])
        let orderDeliveryArg: Double? = nilOrValue(args[11])
        let orderDiscountArg: Double? = nilOrValue(args[12])
        let channelArg: String? = nilOrValue(args[13])
        let customJsonArg: String? = nilOrValue(args[14])
        let recommendedSourceJsonArg: String? = nilOrValue(args[15])
        let streamArg: String? = nilOrValue(args[16])
        let segmentArg: String? = nilOrValue(args[17])
        let shopIdArg: String? = nilOrValue(args[18])
        api.trackPurchase(orderId: orderIdArg, orderPrice: orderPriceArg, items: itemsArg, deliveryType: deliveryTypeArg, deliveryAddress: deliveryAddressArg, paymentType: paymentTypeArg, isTaxFree: isTaxFreeArg, isGiftPackage: isGiftPackageArg, promocode: promocodeArg, orderCash: orderCashArg, orderBonuses: orderBonusesArg, orderDelivery: orderDeliveryArg, orderDiscount: orderDiscountArg, channel: channelArg, customJson: customJsonArg, recommendedSourceJson: recommendedSourceJsonArg, stream: streamArg, segment: segmentArg, shopId: shopIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackPurchaseChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PersonalizationFlutterApiProtocol {
  func onPushReceived(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPushDelivered(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPushClicked(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PersonalizationFlutterApi: PersonalizationFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PersonalizationApiPigeonCodec {
    return PersonalizationApiPigeonCodec.shared
  }
  func onPushReceived(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([shopIdArg, payloadArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPushDelivered(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushDelivered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([shopIdArg, payloadArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPushClicked(shopId shopIdArg: String?, payload payloadArg: [String: String?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.personalization_flutter_sdk.PersonalizationFlutterApi.onPushClicked\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([shopIdArg, payloadArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
